version: '3'
services:
  bot:
    restart: always
    image: web
    volumes:
      - .:/app
    depends_on:
      - web
    command: python bot.py

  web:
    restart: always
    image: web
    build: .
    volumes:
      - .:/app
    # enter ip address of your host here
    command: python manage.py runserver 82.146.46.25:80
