# Generated by Django 3.2.3 on 2021-05-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_role',
            field=models.BooleanField(default=False),
        ),
    ]
