# Generated by Django 3.2.3 on 2021-05-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_question_is_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('middle_name', models.TextField(default='')),
                ('group', models.TextField(default='')),
                ('answer', models.TextField(default='')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.question')),
            ],
        ),
    ]
