# Generated by Django 3.2.3 on 2021-05-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_formanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('middle_name', models.TextField(default='')),
                ('group', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='formanswer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='formanswer',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='formanswer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='formanswer',
            name='surname',
        ),
        migrations.AddField(
            model_name='formanswer',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.attempt'),
        ),
    ]
