# Generated by Django 3.2.3 on 2021-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20210516_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='role',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='attempt',
            name='temperament',
            field=models.TextField(default=''),
        ),
    ]
